version: "2"
services:
  webapp:
    image: dan05011991/demo-frontend:2.27.0
    ports:
      - "9999:80"
    networks:
      - demo
  mocks-mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - demo
  backend:
    image: dan05011991/demo-backend:2.30.3
    ports:
      - "8081:8081"
    networks:
      - demo
networks:
  demo:
